# Практика №2
## Робота з NumPy


In [36]:
import numpy as np

### 1. Створіть вектор (1,2,3) і виведіть його. Виведіть тип масиву.

In [37]:
vector = np.array([1, 2, 3])
print("Вектор:", vector)
print("Тип масиву:", type(vector))

Вектор: [1 2 3]
Тип масиву: <class 'numpy.ndarray'>


### 2. Створіть наступну матрицю і виведіть її:
$$
\left(\begin{array}{cc} 
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{array}\right)
$$ 

In [38]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 3. Створіть нульову матрицю розміром (4,5) - див. numpy.zeros.

In [39]:
zero_matrix = np.zeros((4, 5))
print(zero_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### 4. Створіть одиничну матрицю розміром (3,3) - див. numpy.identity.

In [40]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 5. Виведіть розмір матриці, створеної на 2 кроці.

In [41]:
print(matrix.shape)

(3, 3)


### 6. Створити дві матриці  $A = 
\left(\begin{array}{cc} 
1 & 2 & 3\\
4 & 5 & 6
\end{array}\right)
$ і $B = 
\left(\begin{array}{cc} 
-1 & -2 & -3\\
-4 & -5 & -6
\end{array}\right)
$. Виконайте операції додавання і віднімання для цих двох матриць.

In [42]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
print("Матриця A:")
print(A)

B = np.array([[-1, -2, -3],
              [-4, -5, -6]])
print("\nМатриця B:")
print(B)


C_add = A + B
print("\nСума матриць A і B:")
print(C_add)


C_sub = A - B
print("\nРізниця матриць A і B:")
print(C_sub)

Матриця A:
[[1 2 3]
 [4 5 6]]

Матриця B:
[[-1 -2 -3]
 [-4 -5 -6]]

Сума матриць A і B:
[[0 0 0]
 [0 0 0]]

Різниця матриць A і B:
[[ 2  4  6]
 [ 8 10 12]]


### 7.Для вищезазначених матриць виконайте поелементне множення.

In [43]:
C_mult = A * B
print("Помножені матриці:")
print(C_mult)

Помножені матриці:
[[ -1  -4  -9]
 [-16 -25 -36]]


### 8. До матриці $A$ додайте константу $b=2$.

In [44]:
b = 2
A_plus_b = A + b
print(A_plus_b)

[[3 4 5]
 [6 7 8]]


### 9. Виконайте множення матриці $\left(\begin{array}{cc} 
1 & 2 & 3\\
4 & 5 & 6
\end{array}\right)
$ на матрицю $\left(\begin{array}{cc} 
1 & 1\\
1 & 1\\
1 & 1
\end{array}\right)
$

In [45]:
B = np.array([[1, 1],
              [1, 1],
              [1, 1]])
C = np.dot(A, B)
print("Помножені матриці:")
print(C)

Помножені матриці:
[[ 6  6]
 [15 15]]


### 10. Для двох векторів $v = (1,2,3)$ і $u = (1,1,1)$ знайти Евклідову норму (реалізувати власноруч і перевірити з numpy.linalg.norm)

In [46]:
v = np.array([1, 2, 3])
u = np.array([1, 1, 1])

def euclidean_norm(vector):
    return np.sqrt(np.sum(vector ** 2))

norm_v = euclidean_norm(v)
norm_u = euclidean_norm(u)

norm_v_np = np.linalg.norm(v)
norm_u_np = np.linalg.norm(u)

print("Евклідова норма вектора v (вручну):", norm_v)
print("Евклідова норма вектора v (numpy.linalg.norm):", norm_v_np)
print("")
print("Евклідова норма вектора u (вручну):", norm_u)
print("Евклідова норма вектора u (numpy.linalg.norm):", norm_u_np)

Евклідова норма вектора v (вручну): 3.7416573867739413
Евклідова норма вектора v (numpy.linalg.norm): 3.7416573867739413

Евклідова норма вектора u (вручну): 1.7320508075688772
Евклідова норма вектора u (numpy.linalg.norm): 1.7320508075688772


### 11. Дано вектор $[11,22,33,44,55]$. Необхідно вивести усі елементи від передостаннього елемента до кінця (використайте зріз).

In [47]:
vector = np.array([11, 22, 33, 44, 55])

sliced_vector = vector[-2:]

print("Елементи від передостаннього до кінця:")
print(sliced_vector)

Елементи від передостаннього до кінця:
[44 55]
